### PR TITLE
Fix libstd

### LINKED ISSUE #146: Std support
Unimplemented stuff

```
     14 Drop for trait object
      1 load_value_pair TyLayout { ty: alloc_crate::boxed::Box<dyn alloc_crate::boxed::FnBox<(), Output=()>>, details: LayoutDetails { variants: Single { index: 0 }, fields: Arbitrary { offsets: [Size { raw: 0 }], memory_index: [0] }, abi: ScalarPair(Scalar { value: Pointer, valid_range: 1..=18446744073709551615 }, Scalar { value: Pointer, valid_range: 1..=18446744073709551615 }), align: Align { abi_pow2: 3, pref_pow2: 3 }, size: Size { raw: 16 } } }
      1 Non scalars are not yet supported for "C" abi (core::option::Option<unsafe extern "C" fn(*mut libc::c_void)>) is_return: false
```

<details>

<summary>Edit: hiding this because it is fixed in 1717cc42ef6c5ec0e7d652f6b51cd7fc64990a71</summary>

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IncompatibleDeclaration("__rdl_alloc")', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:480
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   7: rust_begin_unwind
             at libstd/panicking.rs:325
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   9: core::result::unwrap_failed
             at /rustc/65204a97d4876b897df0a70c0b9248b57e2bf057/src/libcore/macros.rs:26
  10: <core::result::Result<T, E>>::unwrap
             at /rustc/65204a97d4876b897df0a70c0b9248b57e2bf057/src/libcore/result.rs:808
  11: rustc_codegen_cranelift::allocator::codegen
             at src/allocator.rs:52
  12: rustc_codegen_cranelift::codegen_mono_items
             at src/lib.rs:498
  13: <rustc_codegen_cranelift::CraneliftCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
             at src/lib.rs:395
```

</details>

Edit2: Patched out variadic functions

### PR DESCRIPTION
**Pull request by bjorn3**
Fixes #146.

r? @sunfishcode for the vararg commit.

### CODE REVIEW

**Comment by bjorn3** [comment]
When testing https://github.com/dropbox/rust-brotli-decompressor it worked perfect.

File: example/mini_core_hello_world.rs [hunk 1]
```diff
@@ -121,6 +121,8 @@ fn main() {
     //return;
 
     unsafe {
+        printf("Hello %s\n\0" as *const str as *const char, "printf\0" as *const str as *const char);
```
Comment (sunfishcode) [inline example/mini_core_hello_world.rs]: In `*const char`, is the `char` here Rust's 4-byte `char` rather than C's 1-byte `char`?

File: example/mini_core.rs [hunk 2]
```diff
@@ -338,6 +338,7 @@ pub mod libc {
     #[link(name = "c")]
     extern "C" {
         pub fn puts(s: *const u8);
+        pub fn printf(format: *const char, ...) -> i32;
```
Comment (bjorn3) [inline example/mini_core.rs]:
```suggestion
        pub fn printf(format: *const i8, ...) -> i32;
```

File: example/mini_core_hello_world.rs (hunk 1 above)
Comment (bjorn3) [reply example/mini_core_hello_world.rs]:
```suggestion
        printf("Hello %s\n\0" as *const str as *const i8, "printf\0" as *const str as *const i8);
```

Comment (bjorn3) [reply example/mini_core_hello_world.rs]: Rust's 4-byte `char`. Changed it to `i8`.

**Comment by bjorn3** [comment]
While simple libstd programs work now, many wont because of unimplemented intrinsics, u128/i128 or SIMD.
